<?php

namespace App\Transformers;

class ErrorTransformer
{

    /**
     * Transforms the errors array that comes from validation
     * @param $errors
     * @return array
     */
    public static function transformValidationErrors($errors)
    {
        // used to store all the warnings generated by the validator
        $formattedErrors = [];

        foreach ($errors->keys() as $key) {
            $error = [
                'code' => null,
                'field' => $key,
                'value' => $errors->first($key)
            ];
            $formattedErrors[] = $error;
        }

        // return errors
        return $formattedErrors;
    }

}